### ISSUE TITLE
Cannot differentiate between disabled and enabled options for git branch

### ISSUE THREAD

**Issue by mddheeraj** [catppuccin/visual-studio#10]
Cannot differentiate between disabled and enabled options for git branch after right-clicking the branch. Below are the screenshots of the default dark and mocha theme.
![couldnotseemouseovergitoptions](https://user-images.githubusercontent.com/20344363/234191043-1daa88b0-0a1f-47bc-9931-19eb2ae90edf.png)
![defaultdark](https://user-images.githubusercontent.com/20344363/234191096-0be220ab-8e08-45d3-a5e9-b4a47bbfbba9.png)

**Comment by mddheeraj** [comment]
Yeah, I see the outline for the enabled options. Thanks for the update!!! :)

**Comment by djflan** [comment]
@mddheeraj Kindly give v1.2.1 a try. I believe this is now fixed. Thanks

**Comment by mddheeraj** [comment]
Thanks @djflan!!! It got fixed!!!!

**Comment by djflan** [comment]
> Thanks @djflan!!! It got fixed!!!!

Glad it's working for you. I know some of the colors are still off on the git buttons.
Working to correct that. I'll need to check the VS Code port to see how they might be handling buttons like that.
