### ISSUE TITLE
Moar colors! - variable/param/event colors

### ISSUE THREAD

**Issue by djflan** [catppuccin/visual-studio#12]
Today, it appears that these are the same color as plain text: 
![image](https://user-images.githubusercontent.com/7758156/235158470-4bcabb63-5e56-4851-a50e-ca01ef8192b2.png)

We can do better than this. The default dark theme colors these:
![image](https://user-images.githubusercontent.com/7758156/235158337-b3619b88-268d-4435-8a52-d05994229e88.png)

We should use the style guide:
https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md

**Comment by eberthold** [comment]
In #22 I did some exploration to bring more colors to the theme. Currently I only touched the Frappé theme and still have a question regarding to xml coloring.

It brings better color support for
- C#
- XML, AXML, XAML
- VsVim extension

it should be fairly easy to port those changes to the other themes as well, once the xml questions are answered
