### ISSUE TITLE
Vertical  Resize Gradients

### ISSUE THREAD

**Issue by djflan** [catppuccin/visual-studio#13]
Investigate addition of vertical gradients to cp themes

**Comment by djflan** [comment]
Samples: 

Mocha-BG-Blue-RoseWater:
![Mocha-BG-Blue-RoseWater](https://user-images.githubusercontent.com/7758156/235310670-798daf38-ba25-4b94-bfb4-684d1354cd02.png)

Mocha-Border-Blue-RoseWater:
![Mocha-Border-Blue-RoseWater](https://user-images.githubusercontent.com/7758156/235310686-98aa706e-0dff-4a90-ae34-0b90e18c0d52.png)

Mocha-Border-Red-RoseWater:
![Mocha-Border-Red-RoseWater](https://user-images.githubusercontent.com/7758156/235310702-b5804e08-f8ac-415e-ac6f-cc699c2d00af.png)

Mocha-Red-Blue-RoseWater:
![Mocha-Red-Blue-RoseWater](https://user-images.githubusercontent.com/7758156/235310705-581d13d1-8df2-45b4-8f04-b34db457dd49.png)

My personal favorite is Mocha-Border-Red-RoseWater.
Need to check with @catppuccin/core to make sure this can be added.

**Comment by sgoudham** [comment]
Just commenting on here for visibility, 

Had a bit of a discussion on the #dev channel on our discord. I pointed out that it would be nice if the gradient matched the rainbow colours defined in the code editor section of our [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md)

In terms of personal preference out of the above, I do like Mocha-Border-Red-RoseWater.
