### ISSUE TITLE
Provide version for Visual Studio 2019

### ISSUE THREAD

**Issue by therealpyro** [catppuccin/visual-studio#19]
Hi,

I'm still running Visual Studio 2019. Would it be possible to provide the catppuccin theme also for VS 2019?

Best,
Stefan

**Comment by djflan** [comment]
@therealpyro I believe so, would you be willing to test a pre-release out to verify it works?

**Comment by therealpyro** [comment]
Sure, no problem. Do you need any special information, log files or similar?
(I have never tested/developed a VS extension, so not sure what you require)

**Comment by djflan** [comment]
You will need to download the file '[Catppuccin.VS.Themes.vsix](https://github.com/catppuccin/visual-studio/releases/download/v1.3.0-pre-vs2019/Catppuccin.VS.Themes.vsix)'

If you then double-click it, you should open it with 'VS Version Selector' (If asked). The VSIX installed should run and prompt you to close Visual Studio and allow it to install.

After allowing the install to complete, you should be able to choose a theme from Tools>Theme>Catppuccin x (Where x is the 'flavor' you want).

Mostly, I'm just looking for some screenshots to verify it is working as intended.

**Comment by therealpyro** [comment]
I have attached some screenshots from a simple C++ project.  One thing I noticed is that the cursor is not translucent and blocks the underlying letter. But I am not sure, if this is an issue with catppuccin or with VsVim (which I also use).

![vs2019-catppuccin-latte](https://github.com/catppuccin/visual-studio/assets/10770407/342b6b5d-1cae-4c88-baf2-48d791d021da)
![vs2019-catppuccin-frappe](https://github.com/catppuccin/visual-studio/assets/10770407/7f5ce8f3-1835-40db-a85d-7bcbe9492588)
![vs2019-catppuccin-macchiato](https://github.com/catppuccin/visual-studio/assets/10770407/49c2fb54-1284-493d-b616-5dae39bfa6dd)
![vs2019-catppuccin-mocha](https://github.com/catppuccin/visual-studio/assets/10770407/bfbedc29-6dd2-4c38-8695-ecca3ee820d4)

**Comment by therealpyro** [comment]
Okay, the black cursor block is due to VsVim (it has its own configuration parameters for the cursor color). If I disable VsVim, I get the default cursor, which looks okay to me.

**Comment by djflan** [comment]
@therealpyro ok, perfect. Looks good. I don't personally use vim (I hate it with passion), but the color scheming for it could be set I think.

In any case, I'm very glad it works - feel free to use that version for now. When the new version is published, you will need to uninstall that version (via extensions menu) and install the new version so updates can be tracked.

Thanks again for helping test it out!

**Comment by djflan** [comment]
@therealpyro New version that supports 2019 is here:
https://marketplace.visualstudio.com/items?itemName=Catppuccin.CatppuccinVS

**Comment by therealpyro** [comment]
Thanks, much appreciated!
