### ISSUE TITLE
New feature visual studio icons

### ISSUE THREAD

**Issue by mddheeraj** [catppuccin/visual-studio#2]
Hello,

This is not an issue, it's a request for new feature. Can we have the icons for visual studio like vs code?

Thank you,
Dheeraj

**Comment by djflan** [comment]
possibly, but I'm unfamiliar with these. Do you have a screenshot?

**Comment by mddheeraj** [comment]
I'm looking for something like this. We have icons package for vscode. https://github.com/catppuccin/vscode-icons

**Comment by djflan** [comment]
got it, will take a look into it

**Comment by djflan** [comment]
@mddheeraj I took a stab at this, but unfortunately, it seems that the [theming tool](https://marketplace.visualstudio.com/items?itemName=idex.colorthemedesigner2022) does not support custom icons.

This still might be possible by manually editing the generated pkgdefs. Mads Kristensen has an [extension that uses custom icons](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.FileIcons).

For now, this is out of scope in regard to theme support - until we have a contributor that can provide a working example of manually edited pkgdef files or appropriate post-build events to do the same - or the theming tool supports image resources/icons natively.

**Comment by mddheeraj** [comment]
Np. Thanks for taking a look at it!!!😃
