### ISSUE TITLE
Cannot differentiate clearer which tab is selected.

### ISSUE THREAD

**Issue by mddheeraj** [catppuccin/visual-studio#29]
Hello, 

We cannot differentiate clearer which tab is selected in NuGet packages for solution window.

Thank You,
Dheeraj
![NuGetPackagesForSolution](https://github.com/catppuccin/visual-studio/assets/20344363/09f67e6f-ee71-4ddd-83a0-b6cc20463ec2)

**Comment by djflan** [comment]
closing. please see the line under the installed tab
