### ISSUE TITLE
Experimental Control Styles in VS 17.9.0 (Preview)

### ISSUE THREAD

**Issue by Cryptoc1** [catppuccin/visual-studio#33]
Visual Studio version 17.9.0 (Preview 1) has introduced a new "Experimental control styles" setting for enabling the upcoming/new UI styling, which includes changes to/new built-in themes.
![image](https://github.com/catppuccin/visual-studio/assets/6041110/862ac9ab-1a87-4bed-922b-dc02211d1702)

The UI Refresh appears to have broken the Catppuccin Theme, for example _Macchiato_ is now a flash-bang:
![image](https://github.com/catppuccin/visual-studio/assets/6041110/9704b26d-1a1b-411a-af46-4ea1f26c8417)

**Comment by djflan** [comment]
naturally, it is broken - it is in preview and isn't supported yet. Labeling this as enhancement.

**Comment by djflan** [comment]
closing this for now - the preview feature doesn't seem to be present in recent VS versions.
