### ISSUE TITLE
C++ highlighting issue

### ISSUE THREAD

**Issue by sayakbiswas** [catppuccin/visual-studio#34]
I'm on the latest release from the marketplace. On a C++ codebase with the dark versions of the theme, the highlighting of same tokens in the code, makes them unreadable. The highlight color needs to be changed

![image](https://github.com/catppuccin/visual-studio/assets/315187/35a8776b-7bf7-44f5-ba23-da6a59854ac3)

**Comment by djflan** [comment]
I can't seem to reproduce this no matter what I try. I'm going to close this issue for now. 
![image](https://github.com/catppuccin/visual-studio/assets/7758156/8986cac3-d991-4ea3-8081-9eb4894afaef)
