### ISSUE TITLE
Option to hide pink borders around input controls

### ISSUE THREAD

**Issue by zd-dalibor** [catppuccin/visual-studio#40]
Is there any way for hiding pink border around input controls, or to make them tinner (like in vscode).

Visual Studio
<img width="584" alt="image" src="https://github.com/catppuccin/visual-studio/assets/226822/e8c91077-da1f-4362-add5-ac3478582fd9">

VS Code
<img width="554" alt="image" src="https://github.com/catppuccin/visual-studio/assets/226822/32188d0b-a7de-4b5b-9c14-f8414f950b3f">

**Comment by djflan** [comment]
unfortunately, not without affecting other controls. You can fork the repo and introduce changes if you wish to customize.
