### ISSUE TITLE
Records are white when used (used to be yellow) - VS version 17.9.4

### ISSUE THREAD

**Issue by MarilynHb** [catppuccin/visual-studio#43]
![image](https://github.com/catppuccin/visual-studio/assets/65784907/0e5369af-0131-4d2e-a2bc-9310471621ed)
Mocha Theme

**Comment by djflan** [comment]
still the same as they were for me 
![image](https://github.com/catppuccin/visual-studio/assets/7758156/73218ae3-c4bb-4124-a94f-57f828d1af04)
Can't reproduce
