### ISSUE TITLE
Interfaces are white when used (used to be yellow) - VS version 17.9.4

### ISSUE THREAD

**Issue by MarilynHb** [catppuccin/visual-studio#44]
![image](https://github.com/catppuccin/visual-studio/assets/65784907/1d54f6d4-5d2d-4fb8-909b-cc1031c02189)
Mocha Theme

**Comment by djflan** [comment]
This is how they appear in the latest version. This isn't reproducible. I'd recommend checking that you are indeed using v1.5.1
![image](https://github.com/catppuccin/visual-studio/assets/7758156/f317274c-67f9-4f61-a29d-e834f09d30cf)
