### ISSUE TITLE
Using namespaces used to be yellow - now they're white

### ISSUE THREAD

**Issue by MarilynHb** [catppuccin/visual-studio#46]
![image](https://github.com/catppuccin/visual-studio/assets/65784907/baf477b8-d5cb-4521-a048-4ff33f4ecbc6)
Mocha Theme

**Comment by djflan** [comment]
still yellow for me. 
![image](https://github.com/catppuccin/visual-studio/assets/7758156/49c5c24f-c0f1-4e4c-bf38-ea696d13af15)
Please verify your version.
