### ISSUE TITLE
Some Controls Difficult to Read

### ISSUE THREAD

**Issue by mahy-ks-hussain** [catppuccin/visual-studio#48]
![image](https://github.com/catppuccin/visual-studio/assets/22604857/96d36172-3a28-43fd-ad78-61a4f496a4a8)

See above image, buttons are quite difficult to read.

I think I've come across some others randomly, so I can either open new issues or update this one as I find them again!

**Comment by djflan** [comment]
yeah this is indeed a known issue. Can just use this ticket. I believe solving this for one button should (in theory) solve it for all
