### ISSUE TITLE
Remove border color on Combo Boxes and Splitters

### ISSUE THREAD

**Issue by ShapePolygon** [catppuccin/visual-studio#49]
![image](https://github.com/catppuccin/visual-studio/assets/40430070/4fd22a36-c7d4-4e17-806e-f96396a5a9b9)
![image](https://github.com/catppuccin/visual-studio/assets/40430070/bfa434f3-d8e8-4a75-8e71-b54d65810ee6)
Please remove border colors on combo boxes and Splitters.

**Comment by djflan** [comment]
The colors make this theme unique. I don't see an adequate justification for removing the border colors.
