### ISSUE TITLE
Whenever an automatic theme update occurs, I lose my custom settings (font  etc)

### ISSUE THREAD

**Issue by pasqualedante** [catppuccin/visual-studio#5]
Every time, after an automatic update occurs, I have to re-set my custom preferences in the fonts section.

Thanks in advance.

**Comment by djflan** [comment]
I understand and this is regrettable, however, this isn't unique to catppuccin. This happens with all custom themes at the moment. Unfortunately, there isn't anything we can do at this time. 

![image](https://user-images.githubusercontent.com/7758156/232481783-70445aec-59ff-45ca-aa9a-cc19ba9a0f9a.png)

The official MS reply:
![image](https://user-images.githubusercontent.com/7758156/232482096-0869cf3d-ed50-420c-bfed-5e7a06083f1e.png)
