### ISSUE TITLE
VS 'Refresh UI' Support

### ISSUE THREAD

**Issue by DylanWhite2** [catppuccin/visual-studio#50]
I am running Visual Studio Professional 17.10.0 Preview 6.0.

When I turn on any of the themes the editor window theming is updated correctly but the surrounding borders/menus/headers are white.  If I enable "Use classic UI control styles (requires restart)" then everything works as expected.  Are there any plans to update the theme to accommodate the new UI?

https://devblogs.microsoft.com/visualstudio/the-visual-studio-ui-refresh-preview-is-here/

Thanks!

**Comment by djflan** [comment]
> I am running Visual Studio Professional 17.10.0 Preview 6.0.
> 
> When I turn on any of the themes the editor window theming is updated correctly but the surrounding borders/menus/headers are white. If I enable "Use classic UI control styles (requires restart)" then everything works as expected. Are there any plans to update the theme to accommodate the new UI?
> 
> https://devblogs.microsoft.com/visualstudio/the-visual-studio-ui-refresh-preview-is-here/
> 
> Thanks!

Support isn't there yet for the new control styles. But we do plan on supporting it. My current VS version doesn't seem to have that as a preview feature. I can't make any promises about when it might come though.

**Comment by djflan** [comment]
I have relabeled the title - this is technically, a feature request vs a bug.

**Comment by DylanWhite2** [comment]
@djflan this issue is regarding the new UI components.  The sticky scroll is fixed but the new UI is still incompatible (for me anyway)

**Comment by djflan** [comment]
@DylanWhite2 Are you on a VS preview release channel? What does the refresh UI look like with the theme applied?
My problem here is that it isn't yet a preview feature in the stable channel, so I don't have a way to actually look at it and make tweaks. 

Sounds like we need to revisit this.

**Comment by DylanWhite2** [comment]
Yes, just on the regular preview builds (currently Visual Studio Professional 2022 17.11.0 Preview 1.1)

![image](https://github.com/user-attachments/assets/25e1a001-4030-4c40-992f-a19d2efe7849)

![image](https://github.com/user-attachments/assets/60a8fd06-356a-4b38-a2ab-1b3cbc623952)

**Comment by moonbeeper** [comment]
Haha, woopsy from my side! Somehow, I misunderstood your issue as "sticky scroll no worky" when, in fact, it was that the ui refresh that doesn't really work with the theme.

I just fixed that (or at least I think I did) with the recent pull request. Test it out and let me know if there's anything I might have missed!

**Comment by djflan** [comment]
We might need to be careful here, as I understand it the preview builds often contain identifiers that aren't finalized yet. Just a thought because we could spend time working on this and it breaks when the feature goes live in the stable channel.

**Comment by moonbeeper** [comment]
Oh, bongos. You're right, they might swap the identifiers for different ones or just be using these as temporary placeholders to replace later with the original ones (the ones with “color” in the name) when they release the refreshed UI. But hey, at least now we have a rough idea of how the theme would look with the new UI!
For now, it might be best to just draft, close or whatever works for my pull request and wait until the stable release.

Ah, and also the author of the issue now has a draft of the theme’s look in the new UI, something is something haha!

**Comment by marss72** [comment]
Hi @djflan. Are there any updates to this? The latest update doesn't seem to add support for the UI refresh.

**Comment by djflan** [comment]
@marss72 none yet, the PR can't be finalized until the 'UI Refresh' is out of preview.

**Comment by marss72** [comment]
> @marss72 none yet, the PR can't be finalized until the 'UI Refresh' is out of preview.

Makes sense. I heard that the UI refresh will be available in the stable channel in VS 2025 (or later). That isn't official however.

**Comment by maftieu** [comment]
VS 2026 is now public https://devblogs.microsoft.com/visualstudio/visual-studio-2026-is-here-faster-smarter-and-a-hit-with-early-adopters/

**Comment by panda7789** [comment]
VS team published guide how to migrate old theme into new one https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/modernize-theme-colors?view=visualstudio

**Comment by ckgamedev** [comment]
@DylanWhite2 et al., I made this change and it's nice enough as a workaround until the fix gets pushed. 

<img width="1766" height="100" alt="Image" src="https://github.com/user-attachments/assets/9062bf36-bf74-4787-904e-99f16bc4cbed" />

It looks all right

<img width="2359" height="1324" alt="Image" src="https://github.com/user-attachments/assets/d14d4230-ac1d-4026-a8d8-ce1c600a0af2" />

Download source, change that line in whatever theme you want, compile (I compiled as a release build), double click to install, restart Visual Studio.
