### ISSUE TITLE
Latte bug

### ISSUE THREAD

**Issue by Loongtech** [catppuccin/visual-studio#55]
In Visual Studio 2022, when using the plugin: TONGYI Lingma 2022, a purple background color appears in the Chinese part of the plugin's display interface, which seriously affects reading 

![微信图片_20240816141708](https://github.com/user-attachments/assets/5c20cea7-cc7c-4fba-b1da-15d9fdd465f7)

**Comment by djflan** [comment]
@Loongtech Unfortunately, I don't have that plugin installed. You're welcome to take a stab at fixing this in a pr and I will merge, but I can't support this out-of-the-box.
