### ISSUE TITLE
Tabs not highlighted when I mouse over the tabs.

### ISSUE THREAD

**Issue by mddheeraj** [catppuccin/visual-studio#6]
Hello,

I'm unable to view the tabs highlighted when I mouse over them. I have attached both default dark mode and the mocha screenshots.

Thank You,
Dheeraj
![mochathememouseovertabsnothiglighted](https://user-images.githubusercontent.com/20344363/232861081-03883d36-d812-4cbb-ba62-1d83f22c2d7c.png)
![visualstudiodarkmodemouseovertabs](https://user-images.githubusercontent.com/20344363/232861087-dc3a3089-c820-444e-b429-774c89f2a092.png)

**Comment by djflan** [comment]
Added to better-inlay-hints-colors:
![image](https://user-images.githubusercontent.com/7758156/232887475-6210888d-78a3-4f2f-b203-244a0f69d007.png)

Also added rainbow braces:
![image](https://user-images.githubusercontent.com/7758156/232888598-c3570f40-ecb9-421e-9816-c6a31492efeb.png)

see:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.RainbowBraces

**Comment by mddheeraj** [comment]
The issue is different. Does the Rainbow braces will fix the highlighted color change for the tabs?

**Comment by djflan** [comment]
@mddheeraj No, it is unrelated. There are two additions, the first of which is the issue you pointed out.

**Comment by djflan** [comment]
Yes, when the next version is published
