### ISSUE TITLE
Display issue with Visual Studio 2022 17.12

### ISSUE THREAD

**Issue by wbpayne22902** [catppuccin/visual-studio#60]
In VS 2022 17.12.0, the arrows to hide code blocks are appearing with a solid white background as shown in the screenshot attached.
![Screenshot 2024-11-12 214830](https://github.com/user-attachments/assets/f817da68-bd1b-4dad-9574-0b066b521f99)

**Comment by wbpayne22902** [comment]
17.12 had already been released as a final version when I posted the issue.

**Comment by djflan** [comment]
> 17.12 had already been released as a final version when I posted the issue. It was released on November 12, 2024. I request this be reopened as the rationale for closing the issue doesn't exist.

 I'll update my copy and recheck this. Thanks

**Comment by wbpayne22902** [comment]
No problem.  Something definitely changed in 17.12, because Catppuccin is not the only theme with the same issue.

**Comment by djflan** [comment]
@wbpayne22902 Yeah... I'm definitely seeing the same issue here which is unfortunate. Seems like they have added some UI elements in this release.

**Comment by wbpayne22902** [comment]
I can comment that @serge-linnet's PR #61 fixes this issue.
