### ISSUE TITLE
Colours not importing properly

### ISSUE THREAD

**Issue by Faunsce** [catppuccin/visual-studio#7]
This may possibly be an error on my part but I have a fresh install of VS and these colours are all off and my other themes don't do this so there may be an error. Hopefully this isn't just me and is something that can be resolved by some change on the plugin's end.

OS : Windows 10 Pro N V 19044.2846
CPU : R9 5900X
IDE : VS 2022 Community 64-bit Version 17.4.5

Attached below are the results right after installing and rebooting. No matter how many times I redo this the colours are all messed up. I also have high-contrast off. I tried to see if turning it on would help but alas it does not.
![image](https://user-images.githubusercontent.com/24751378/233812163-5739da4b-1585-413e-a603-dd82a0cb39e4.png)

**Comment by djflan** [comment]
yeah, that doesn't look right... not sure what's up there. That said, I don't think I've tested any C++ using the theme. I'll see what I get.

**Comment by djflan** [comment]
Unfortunately, I can't seem to reproduce this. My best guess is you might have another extension that is messing with the styling or the fallback settings are not being applied properly. I did recently correct a bug where the themes were not gracefully falling back to their respective counterparts:

Mocha -> Dark
Macchiato -> Dark
Frappe -> Dark
Latte -> Light

This will be included in the 1.2.0 release. 
This is an example with the "rainbow braces" extension:
![image](https://user-images.githubusercontent.com/7758156/233845134-cda1f633-b1d4-4505-a0a3-935b044c6677.png)

For now, Ill consider this issue resolved - we can revisit after release.

**Comment by Faunsce** [comment]
Did some testing and the new version seems to fix this, thanks @djflan !

**Comment by djflan** [comment]
@Faunsce glad its fixed :)
